name: Build and Test-run

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        
        include:
          # Windows
          - os: windows-latest
            compiler: cl
            cpp_compiler: cl
          # Ubuntu (GCC)
          - os: ubuntu-latest
            compiler: gcc
            cpp_compiler: g++
          # Ubuntu (Clang)
          - os: ubuntu-latest
            compiler: clang
            cpp_compiler: clang++
          # macOS (Clang)
          - os: macos-latest
            compiler: clang
            cpp_compiler: clang++


    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        # Змінюємо c_compiler на compiler (новий ключ у include)
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.compiler }} 
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }} --output-on-failure
